In [1]:
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('data/eng_subtitles_database.db')

# Create a cursor object to execute SQL queries
cursor = conn.cursor()

# Query to retrieve table names
query = "SELECT name FROM sqlite_master WHERE type='table';"

# Execute the query
cursor.execute(query)

# Fetch all the results
tables = cursor.fetchall()

# Close the cursor and the connection
cursor.close()
conn.close()

# Extract table names from the fetched results
table_names = [table[0] for table in tables]

# Display the table names
print("Table names:")
for name in table_names:
    print(name)

Table names:
zipfiles

In [2]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('data/eng_subtitles_database.db')

# Query to select all data from a specific table (replace 'your_table_name' with the actual table name)
query = "SELECT * FROM zipfiles;"

# Use pandas to read the data into a DataFrame
df = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

# Now you can work with the DataFrame 'df' as needed
df.head()  # Display the first few rows of the DataFrame

,num,name,content
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...

In [3]:
df

,num,name,content
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...
...,...,...,...
82493,9521935,the.prophets.game.(2000).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xb8\xa6\x...
82494,9521937,west.beirut.(1998).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x13\x97\x...
82495,9521938,frankenstein.the.true.story.(1973).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00$\x97\x9aV...
82496,9521940,frankenstein.the.true.story.(1973).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x97\x...
82497,9521941,zombie.island.massacre.(1984).eng.1cd,"b'PK\x03\x04\x14\x00\x00\x00\x08\x00,\x97\x9aV..."

In [4]:
df_new = df.sample(frac = 0.05)

In [5]:
df_new.shape

(4125, 3)

In [6]:
import zipfile
import io

count = 0

def decode_method(binary_data):
    global count
    # Decompress the binary data using the zipfile module
    # print(count, end=" ")
    count += 1
    with io.BytesIO(binary_data) as f:
        with zipfile.ZipFile(f, 'r') as zip_file:
            # Assuming there's only one file in the ZIP archive
            subtitle_content = zip_file.read(zip_file.namelist()[0])
    
    # Now 'subtitle_content' should contain the extracted subtitle content
    return subtitle_content.decode('latin-1')  # Assuming the content is UTF-8 encoded text

In [7]:
df_new['file_content'] = df_new['content'].apply(decode_method)

df_new.head()

,num,name,content,file_content
14483,9241559,hetty.wainthropp.investigates.s02.e04.the.astr...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00s\x98\x99V...,"Ã¯Â»Â¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch..."
28071,9293630,suck.(2009).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xe3\xa5\x...,"1\r\n00:00:09,507 --> 00:00:28,499\r\n\r\n2\r\..."
46436,9375173,rise.of.empires.ottoman.s02.e02.troubled.water...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00r\x13\x9aV...,"Ã¯Â»Â¿1\r\n00:00:06,000 --> 00:00:12,074\r\napi.O..."
71413,9475143,the.watchful.eye.s01.e09.the.serpents.tooth.(2...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x8d]\x9aV...,"Ã¯Â»Â¿1\r\n00:00:00,139 --> 00:00:02,139\r\n<i>Pr..."
2927,9194232,madam.secretary.s05.e14.something.better.(2019...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xfd\x8b\x...,"Ã¯Â»Â¿1\r\n00:00:02,102 --> 00:00:06,039\r\n[Ã¢Â™Âª ..."

In [8]:
import re
from bs4 import BeautifulSoup

def clean(text):
    soup = BeautifulSoup(text)
    return re.sub("[^a-z A-Z]", "",soup.text)

In [6]:
from tqdm import tqdm
tqdm.pandas()

In [10]:
df_new['file_content'] = df_new['file_content'].progress_apply(clean)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4125/4125 [01:06<00:00, 62.40it/s]

In [11]:
df_new.head()

,num,name,content,file_content
14483,9241559,hetty.wainthropp.investigates.s02.e04.the.astr...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00s\x98\x99V...,Watch any video online with OpenSUBTITLESFre...
28071,9293630,suck.(2009).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xe3\xa5\x...,This is the Rockin Roger MorningShow laten...
46436,9375173,rise.of.empires.ottoman.s02.e02.troubled.water...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00r\x13\x9aV...,apiOpenSubtitlesorg is deprecated pleaseimpl...
71413,9475143,the.watchful.eye.s01.e09.the.serpents.tooth.(2...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x8d]\x9aV...,Previously on TheWatchful Eye Morgan Its n...
2927,9194232,madam.secretary.s05.e14.something.better.(2019...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xfd\x8b\x...,TALKING HEADSBURNING DOWN THE HOUSE apiOpe...

In [12]:
df_new['file_content'] = df_new['file_content'].str.lower()

In [13]:
def chuck_df(corpous, id_col, chunk_size=300):
    data = []
    for doc, id in zip(corpous, id_col):
        words = doc.split()
        for i in range(0, len(words), chunk_size):
            chunk = ' '.join(words[i : i+chunk_size])
            data.append((id, chunk))
    df = pd.DataFrame(data, columns=['ID', 'Text'])
    return df

In [14]:
chucked_df = chuck_df(df_new['file_content'],df_new['num'])

In [15]:
chucked_df

            ID                                               Text
0      9241559  watch any video online with opensubtitlesfree ...
1      9241559  speak as i find our fees arent highdespite my ...
2      9241559  a private consultation its expensive but well ...
3      9241559  drive his diary when my father retired he and ...
4      9241559  like thisyouve no idea of the wastage one step...
...        ...                                                ...
63605  9471321  are you saying sit down sit down youre going t...
63606  9471321  here whats upwhats up nothingrelax relax what ...
63607  9471321  dad had taken it do you think someone tipped o...
63608  9471321  are you eh who are you from now on corbaln is ...
63609  9471321  it good luck that cop creeps me out can we tru...

[63610 rows x 2 columns]

In [16]:
merge_df = chucked_df.merge(df_new, left_on='ID',right_on='num', how='left')

In [17]:
final = merge_df[['ID','name','Text']]

In [18]:
final.shape

(63610, 3)

In [19]:
final.head()

,ID,name,Text
0,9241559,hetty.wainthropp.investigates.s02.e04.the.astr...,watch any video online with opensubtitlesfree ...
1,9241559,hetty.wainthropp.investigates.s02.e04.the.astr...,speak as i find our fees arent highdespite my ...
2,9241559,hetty.wainthropp.investigates.s02.e04.the.astr...,a private consultation its expensive but well ...
3,9241559,hetty.wainthropp.investigates.s02.e04.the.astr...,drive his diary when my father retired he and ...
4,9241559,hetty.wainthropp.investigates.s02.e04.the.astr...,like thisyouve no idea of the wastage one step...

In [22]:
final.to_csv(r'final1.csv',index=False)

In [36]:
# !pip install sympy

Requirement already satisfied: sympy in c:\users\aravi\appdata\local\programs\python\python310\lib\site-packages (1.12)
Requirement already satisfied: mpmath>=0.19 in c:\users\aravi\appdata\local\programs\python\python310\lib\site-packages (from sympy) (1.3.0)

In [2]:
# !pip install 'transformers[tf-cpu]'

ERROR: Invalid requirement: "'transformers[tf-cpu]'"

In [8]:
from huggingface_hub import hf_hub_download
hf_hub_download(repo_id="bert-base-uncased", filename="config.json")

'C:\\Users\\aravi\\.cache\\huggingface\\hub\\models--bert-base-uncased\\snapshots\\86b5e0934494bd15c9632b12f734a8a67f723594\\config.json'

In [35]:
model.summary()

Model: "tf_bert_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 bert (TFBertMainLayer)      multiple                  109482240

=================================================================
Total params: 109482240 (417.64 MB)
Trainable params: 109482240 (417.64 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
import pandas as pd

df = pd.read_csv(r'final1.csv')

In [118]:
df = df[df['Text'].str.len() > 100]

,ID,name,Text
0,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,hey guys all greeting we need to talk toyou ab...
1,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,needlessturkey murder day hey guys i orderedso...
2,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,from the adoption agencyand its been weeks im ...
3,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,listen i think we got to go this place is real...
4,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,when i was herefor holidays on ice i was sitti...
5,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,alicia mayemorys outfit you guys thereare peop...
6,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,we playrock paper scissors and whoever loses g...
7,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,i know i stillhave my old key ooh we can just ...
8,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,of this okay we said were sorry its thanksgivi...
9,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,is over the vein has spoken its really startin...
10,9264563,la.brea.s02.e02.the.cave.(2022).eng.1cd,eerie music according to this mapthe one in se...
11,9264563,la.brea.s02.e02.the.cave.(2022).eng.1cd,eve who are you my name is gavin harris this i...
...,...,...,...
63534,9326881,the.web.(1947).eng.1cd,if you give me away ill be sunkin more ways th...
63535,9326881,the.web.(1947).eng.1cd,address you remember the address yes youre sur...
63536,9326881,the.web.(1947).eng.1cd,at all what about the girl what about her shes...
63537,9326881,the.web.(1947).eng.1cd,difference does it make for a momenti thought ...
63538,9326881,the.web.(1947).eng.1cd,hello damico hows business theres your body ov...
63539,9326881,the.web.(1947).eng.1cd,you find the money she had it on her she was b...
63540,9326881,the.web.(1947).eng.1cd,kroner charles and now me lieutenant this is v...
63541,9326881,the.web.(1947).eng.1cd,probably dead too otherwise how could colby be...
63542,9416924,red.shoe.diaries.s01.e06.another.womans.lipsti...,wind blowing pen scrapes against newspaper sul...
63543,9416924,red.shoe.diaries.s01.e06.another.womans.lipsti...,narrating who was she what did she have that i...
63544,9416924,red.shoe.diaries.s01.e06.another.womans.lipsti...,goodbye door closes police car sirens wailing ...
63545,9416924,red.shoe.diaries.s01.e06.another.womans.lipsti...,away i know the question is which one of us we...

In [15]:
df.head()

,ID,name,Text
0,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,hey guys all greeting we need to talk toyou ab...
1,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,needlessturkey murder day hey guys i orderedso...
2,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,from the adoption agencyand its been weeks im ...
3,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,listen i think we got to go this place is real...
4,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,when i was herefor holidays on ice i was sitti...

In [16]:
from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

In [8]:
from chromadb import Documents, EmbeddingFunction, Embeddings

class MyEmbeddingFunction(EmbeddingFunction):
    def __call__(self, input: Documents) -> Embeddings:
        # embed the documents somehow
        tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        model = BertModel.from_pretrained('bert-base-uncased')
        encoding = tokenizer.batch_encode_plus(
            [Documents],                    # List of input texts
            padding=True,              # Pad to the maximum sequence length
            truncation=True,           # Truncate to the maximum sequence length if necessary
            return_tensors='pt',      # Return PyTorch tensors
            add_special_tokens=True    # Add special tokens CLS and SEP
        )
        input_ids = encoding['input_ids']
        attention_mask = encoding['attention_mask']
        with torch.no_grad():
            outputs = model(input_ids, attention_mask=attention_mask)
            word_embeddings = outputs.last_hidden_state
        encoded_text = tokenizer.encode(text, return_tensors='pt')
        decoded_text = tokenizer.decode(input_ids[0], skip_special_tokens=True)
        tokenized_text = tokenizer.tokenize(decoded_text)
        sentence_embedding = word_embeddings.mean(dim=1)

        embedding = sentence_embedding.tolist()[0]
        return embedding

In [17]:
def embeddeing(text):
    encoding = tokenizer.batch_encode_plus(
        [text],                    # List of input texts
        padding=True,              # Pad to the maximum sequence length
        truncation=True,           # Truncate to the maximum sequence length if necessary
        return_tensors='pt',      # Return PyTorch tensors
        add_special_tokens=True    # Add special tokens CLS and SEP
    )
    input_ids = encoding['input_ids']
    attention_mask = encoding['attention_mask']
    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)
        word_embeddings = outputs.last_hidden_state
    encoded_text = tokenizer.encode(text, return_tensors='pt')
    decoded_text = tokenizer.decode(input_ids[0], skip_special_tokens=True)
    tokenized_text = tokenizer.tokenize(decoded_text)
    sentence_embedding = word_embeddings.mean(dim=1)

    return sentence_embedding.tolist()[0]

In [18]:
embedd = []
embedd.append(df['Text'].progress_apply(embeddeing))

  0%|â–Ž                                                                          | 212/63546 [03:58<14:34:28,  1.21it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (825 > 512). Running this sequence through the model will result in indexing errors
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 63546/63546 [11:47:40<00:00,  1.50it/s]

In [47]:
new = embedd[0].tolist()

In [44]:
import numpy as np

np.save('embed.npy',embedd)

In [78]:
#import chromadb.utils.embedding_functions as embedding_functions
#huggingface_ef = embedding_functions.HuggingFaceEmbeddingFunction(
#    api_key="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",
#    model_name="google-bert/bert-base-uncased"
#)

In [80]:
#embd_func = MyEmbeddingFunction()
#collection = chroma_client.create_collection(name="my_collection1", embedding_function=huggingface_ef , metadata={"hnsw:space": "cosine"})

In [48]:
import chromadb
chroma_client = chromadb.PersistentClient(path="./DB")

In [89]:
collection = chroma_client.create_collection(name="Movies", metadata={"hnsw:space": "cosine"})

In [94]:
batch = 5460
for j in range(0,len(df),batch):
    end = min(j+batch, len(df))
    collection.add(
    documents=df.Text.to_list()[j:end],
    metadatas=[{'name':i,'Movie ID':j} for i,j in zip(df.name.to_list(), df.ID.astype('str').to_list())][j:end],
    embeddings = new[j:end],
    ids=df.index.astype('str').to_list()[j:end]
    )

In [122]:
query_emd = embeddeing('if were right and you do nothing people will die')
collection.query(
    query_embeddings=[query_emd],
    n_results=5,
)

{'ids': [['28953', '28340', '32181', '8744', '4623']],
 'distances': [[0.21905159950256348,
   0.22617018222808838,
   0.2322596311569214,
   0.23355722427368164,
   0.2505359649658203]],
 'metadatas': [[{'Movie ID': '9493918',
    'name': 'the.hexer.s01.e01.dziecinstwo.(2002).eng.1cd'},
   {'Movie ID': '9237710',
    'name': 'kung.fu.s02.e08.the.soldier.(1973).eng.1cd'},
   {'Movie ID': '9386848', 'name': 'romulus.(2020).eng.1cd'},
   {'Movie ID': '9511701', 'name': 'pilgrimage.(2017).eng.1cd'},
   {'Movie ID': '9437714',
    'name': '1923.s01.e07.the.rule.of.five.hundred.(2023).eng.1cd'}]],
 'embeddings': None,
 'documents': [['a white wolf what should we do we need to deal with this only the truth can heal us and purge the dishonour assemble the whole council and then bring the holy druid and now listen you know i didnt have to come but im here you broke our sacred law you dont have the right to accuse me you are only poor weak old man i despise you you drew your sword on humans here is the evidence you killed the parents of these children you brought disgrace to our mission you are cursed a thousand times i know i know i know this is your evidence a pair of elves and a few bastards give yourself to gods judgementgive yourself to the test of dreams i have never given myselfto your tricks and superstitions and i never will then leave us falwick count of moen you were and are an evil man you were never a witcher what did you say be gone give up your swords boy one day i will kill you its you that will die by my hand i want to be a witcher text and timing revisions by peacht',
   'the courage to kill an enemy who is a man like yourself you really didnt take part in that battle no when am i gonna learn the secret to see the man to point the gun and to squeeze the trigger why must you learn such a secret because until i do ill remain a coward to endanger yourself to save anothers life is this the act of a coward its not enough for a soldier it is enough for a man ill say goodbye here what will you tell your captain ill tell him what happened will you be a soldier still no no ill look for a different way to be of use something im more suited to you will find it watch any video online with opensubtitlesfree browser extension osdblinkext',
   'bond is the only thingthat makes me human without you i am just an animal if i keep you far from deathfar from my fury i will stay alive too i do not belong to you i am free and the day will come when your poisonand your ropes cannot stop me and that day i will kill you because you are the cause of all evil you stay back this time i shall speak i order you to let us pass does he make you talk because he isashamed of what you are doing nobody here needs to be ashamed nobody wants to hurt you i see clubs in their hands dont lie look at yourself tarinkriyou are few against the will of many rumia is with me if you take the salt from now onyou will be alone and destined for death enough be prepared for the worst they are my brothers my pack they are my pack herennis and they will do what i say dont let them pass this is the last chance i give youtarinkri get out of the way i no longer take orders from thosewho have no respect for the goddess take them away you are a dog herennis a traitor dog why are you letting them do this yemos not participating is not enoughthe goddess will never forgive you wiros knows our way forward the pack must remain loyal to him there is no pack anymore herennisbrothers will kill each other there is no other way help me i thought about your words i needed little time to decide what to do i saw the truth in your eyes in your words there were no shadows everything appeared clear like the water of the sacred river you are afraid of me you',
   'will not our need is great you will not brother you disobey me again you are not worthy to carry the relicthere is something in you boy something evil wait was there truth to what he said about your father he sheltered heretics helped them escape trial i served the church tothe best of my ability my conscience is clear what else do you wish to know boy nothing i asked him to repent but he did not right till the end he refused tobelieve that he had done anything wrong i learned somethingvery important that day it wasnt his faith inthe church that he lost it was his fear of it what are you saying no push in the name of christ go with god dugald hell do you hear them did you hear the bells the bell will inspirean army of men like him men will retake jerusalemmen who will retake the world the heretics the infidels the faithless if they will not hear thetruth they will suffer all doubt will be swapped away stand with the church and livestand against it and be crushed what are you doing no this is gods stone im giving it back to him no the devil has you boy support us and become vip member to remove all ads from wwwopensubtitlesorg',
   'in argentina served one in peru the philippines all populated withpeople like you people who now thrive they thrive build cities grow crops all in the bosom of christ they followed ourteachings and they prosper you reject them fight them and suffering is your reward salvation awaits in the light and yet you people choose darkness seek it crave it i think your souls havebeen spoken for already i think the devil has them you dont need schools you need exorcisms you are a priest i am a holy man yes but youve killed in the name of god stolen what have i stolen the land you sit on i have stolen nothing if you hadnt stolen ityou wouldnt be here youd be somewhere else i dont understandyour pagan logic your god has all these laws i know them i studied them youre supposedto teach his laws but you break themto teach them so the laws meansnothing to you which means your god doesntexist and you know it blasphemy yougodless heathen i think the world will be abetter place without you in it without any of you our father who art in heaven look at me when i speak hallowed be thy name thy kingdom comethy will be done on earth as it is in heaven if his will is done on earthand my knife is to your throat this must be whatyour god wants can you walk i can run if you want we let the horses run theres two more priestslooking for teonna i saw the tracks which way did they go hank in the badlands by the red creek they will stop for the night we wont what do we do with him go wait with the horses what did you do ate his soul we must']],
 'uris': None,
 'data': None}

In [72]:
df.head(10)

,ID,name,Text
0,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,hey guys all greeting we need to talk toyou ab...
1,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,needlessturkey murder day hey guys i orderedso...
2,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,from the adoption agencyand its been weeks im ...
3,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,listen i think we got to go this place is real...
4,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,when i was herefor holidays on ice i was sitti...
5,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,alicia mayemorys outfit you guys thereare peop...
6,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,we playrock paper scissors and whoever loses g...
7,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,i know i stillhave my old key ooh we can just ...
8,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,of this okay we said were sorry its thanksgivi...
9,9338372,friends.s10.e08.the.one.with.the.late.thanksgi...,is over the vein has spoken its really startin...